---
title: "RSSkillAssessment_R"
author: "Joey Li"
date: "July 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 0. Import Dataset and Libraries
```{r}
rm(list=ls())
library(readxl)
library(tidyverse)
library(ggplot2)

df<- read_excel("RiskSpanSkillsAssessment.xlsx", sheet = "Data")
attach(df)
summary(df)
head(df)
colnames(df)
```

# REPORT 1: Data by Lender Institution Type
```{r}
r11 <- table(LENDER_INST_TYPE_DESCRIPTION)
r11 <- as.data.frame(r11)

r12 <- aggregate(CURRENT_BALANCE ~ LENDER_INST_TYPE_DESCRIPTION, FUN=function(x) {sum(x)/length(x)})

r13 <- aggregate(CURRENT_BALANCE ~ LENDER_INST_TYPE_DESCRIPTION, FUN=max)

r14 <- aggregate(CURRENT_BALANCE ~ LENDER_INST_TYPE_DESCRIPTION, FUN=min)

report1 <- cbind(r11,r12$CURRENT_BALANCE,r13$CURRENT_BALANCE,r14$CURRENT_BALANCE)
colnames(report1) <-c("LENDER_INST_TYPE_DESCRIPTION","LOAN_COUNT","AVERAGE_CURRENT_BALANCE","MAX_CURRENT_BALANCE","MIN_CURRENT_BALANCE")
report1
```

# REPORT 2: Data by LTV (Loan to Value) Cohorts
```{r}
df$LTV_COHORTS<-"<= 85%"
df$LTV_COHORTS[LTV <= 90 & LTV >85] <- ">85% and <= 90%"
df$LTV_COHORTS[LTV <= 95 & LTV >90] <- ">90% and <= 95%"
df$LTV_COHORTS[LTV > 95] <- "> 95%"

r21 <- table(df$LTV_COHORTS)
r21 <- as.data.frame(r21)
r22 <- aggregate(CURRENT_BALANCE ~ df$LTV_COHORTS, FUN=function(x) {sum(x)/length(x)})
r23 <- aggregate(CURRENT_BALANCE ~ df$LTV_COHORTS, FUN=max)
r24 <- aggregate(CURRENT_BALANCE ~ df$LTV_COHORTS, FUN=min)

report2 <- cbind(r21,r22$CURRENT_BALANCE,r23$CURRENT_BALANCE,r24$CURRENT_BALANCE)
colnames(report2) <-c("LTV_COHORTS","LOAN_COUNT","AVERAGE_CURRENT_BALANCE","MAX_CURRENT_BALANCE","MIN_CURRENT_BALANCE")
report2 <- report2[c(1,3,4,2),]
report2
```

# REPORT 3: Data by Loan Age Cohort (Loan Age = 6/1/2013 minus LOAN_ORIG_DATE in months)
```{r}
df$LOAN_AGE <- difftime(df$START_DATE, df$LOAN_ORIG_DATE,units = "weeks")/4
df$LOAN_AGE <- round(df$LOAN_AGE, digits=2)

df$LOAN_AGE_COHORTS<-"Unknown"
df$LOAN_AGE_COHORTS[df$LOAN_AGE < 10 & df$LOAN_AGE >= 0] <- "0 - 9 Months"
df$LOAN_AGE_COHORTS[df$LOAN_AGE < 20 & df$LOAN_AGE >= 10] <- "10 - 19 Months"
df$LOAN_AGE_COHORTS[df$LOAN_AGE < 30 & df$LOAN_AGE >= 20] <- "20 - 29 Months"
df$LOAN_AGE_COHORTS[df$LOAN_AGE < 40 & df$LOAN_AGE >= 30] <- "30 - 39 Months"
df$LOAN_AGE_COHORTS[df$LOAN_AGE >= 40] <- ">= 40 Months"

r31 <- table(df$LOAN_AGE_COHORTS)
r31 <- as.data.frame(r31)
r32 <- aggregate(CURRENT_BALANCE ~ df$LOAN_AGE_COHORTS, FUN=function(x) {sum(x)/length(x)})
r33 <- aggregate(CURRENT_BALANCE ~ df$LOAN_AGE_COHORTS, FUN=max)
r34 <- aggregate(CURRENT_BALANCE ~ df$LOAN_AGE_COHORTS, FUN=min)

report3 <- cbind(r31,r32$CURRENT_BALANCE,r33$CURRENT_BALANCE,r34$CURRENT_BALANCE)
colnames(report3) <-c("LOAN_AGE_COHORTS","LOAN_COUNT","AVERAGE_CURRENT_BALANCE","MAX_CURRENT_BALANCE","MIN_CURRENT_BALANCE")
report3 <- report3[c(6,2,3,4,5,1),]
report3
```

# REPORT 4: Create a Crosstab Report- SUM of CURRENT_UPB by LTV Cohorts and FICO Cohorts
```{r}
df$FICO_COHORTS<-"< 600"
df$FICO_COHORTS[df$FICO_SCORE <= 699 & df$FICO_SCORE > 600] <- "600 - 699"
df$FICO_COHORTS[df$FICO_SCORE <= 799 & df$FICO_SCORE > 700] <- "700 - 799"
df$FICO_COHORTS[df$FICO_SCORE >= 800] <- ">= 800"

report4 <- with(df, tapply(CURRENT_BALANCE, list(FICO_COHORTS, LTV_COHORTS), FUN=sum))
report4 <- report4[c(1,3,4,2),c(1,3,4,2)]
report4
```

# REPORT5: Create a bar graph in your statistical program of Report 4.
```{r}
report5 <- aggregate(CURRENT_BALANCE ~ LTV_COHORTS + FICO_COHORTS, data=df, FUN=sum)

plot <- ggplot(report5, aes(fill = LTV_COHORTS, y=CURRENT_BALANCE, x=FICO_COHORTS)) + 
    geom_bar(position="dodge", stat="identity")
plot
```
